{{- if .Values.odoo.database.adminSecretNamespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-db-jobs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
{{- end }}
