apiVersion: v2
name: odoo-openapi
description: A Helm chart for Odoo OpenAPI Tool Server
version: 0.1.3
appVersion: "1.0.0"
type: application
home: https://github.com/bemade/helm-charts
sources:
  - https://github.com/bemade/helm-charts
maintainers:
  - name: Bemade Inc.
    url: https://bemade.org
    email: marc@bemade.org
