apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  masterPassword: {{ .Values.odoo.masterPassword | quote }}
data:
  {{- $secretObj := lookup "v1" "Secret" .Release.Namespace "credentials" }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $superUserPassword := (get $secretData "superUserPassword") | default (randAlphaNum 32 | b64enc) }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  superUserPassword: {{ $superUserPassword | quote }}
  password: {{ $password | quote }}
