apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}
  odooPassword: {{ randAlphaNum 16 | b64enc | quote }}

