{{- if .Values.odoo.imageRegistry.url }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\", \"auth\": \"%s\"}}}" .Values.odoo.imageRegistry.url .Values.odoo.imageRegistry.username .Values.odoo.imageRegistry.password .Values.odoo.imageRegistry.email (printf "%s:%s" .Values.odoo.imageRegistry.username .Values.odoo.imageRegistry.password | b64enc) | b64enc }}
{{- end }}
