apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: odooinstances.odoo.bemade.org
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: odoo.bemade.org
  names:
    kind: OdooInstance
    listKind: OdooInstanceList
    plural: odooinstances
    singular: odooinstance
    shortNames:
      - odoo
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
              properties:
                version:
                  type: string
                  description: "Odoo version to deploy (e.g. '17.0')"
                adminSecret:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name of the secret containing the Odoo admin password"
                    key:
                      type: string
                      description: "Key in the secret containing the Odoo admin password"
                      default: "admin-password"
                image:
                  type: string
                  description: "Odoo image to use (defaults to odoo:version)"
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                  description: "Number of Odoo replicas"
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string

                filestore:
                  type: object
                  properties:
                    storageSize:
                      type: string
                      default: "10Gi"
                    storageClass:
                      type: string
                    snapshotClass:
                      type: string
                    snapshotSchedule:
                      type: string
                      description: "Cron expression for automatic snapshots"
                addons:
                  type: array
                  items:
                    type: object
                    required:
                      - repo
                    properties:
                      repo:
                        type: string
                        description: "Git repository URL"
                      branch:
                        type: string
                        default: "main"
                      path:
                        type: string
                        description: "Path within the repository"
                      credentials:
                        type: string
                        description: "Reference to a secret with Git credentials"
                ingress:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    hostname:
                      type: string
                    className:
                      type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    tls:
                      type: boolean
                      default: true
                    tlsSecret:
                      type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                          configMapKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Deploying
                    - Running
                    - Failed
                message:
                  type: string
                ready:
                  type: boolean
                url:
                  type: string
                lastBackup:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: URL
          type: string
          jsonPath: .status.url
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
