apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-operator.fullname" . }}
  labels:
    {{- include "odoo-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "odoo-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "odoo-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: webhook
              containerPort: 443
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.operator.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.operator.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          env:
            - name: WEBHOOK_CERT_PATH
              value: "/tmp/k8s-webhook-server/serving-certs/tls.crt"
            - name: WEBHOOK_KEY_PATH
              value: "/tmp/k8s-webhook-server/serving-certs/tls.key"
            - name: WATCH_NAMESPACE
              {{- if .Values.rbac.clusterWide }}
              value: ""
              {{- else }}
              value: {{ .Release.Namespace }}
              {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "odoo-operator.fullname" . }}
            - name: DEFAULT_ODOO_IMAGE
              value: {{ .Values.defaults.odooImage }}
            - name: DEFAULT_STORAGE_CLASS
              value: {{ .Values.defaults.storageClass }}
            - name: DEFAULT_INGRESS_CLASS
              value: {{ .Values.defaults.ingressClass }}
            # Database configuration
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_ADMIN_USER
              value: {{ .Values.database.adminUser | quote }}
            - name: DB_ADMIN_PASSWORD_SECRET
              value: {{ .Values.database.adminPasswordSecret.name | quote }}
            - name: DB_ADMIN_PASSWORD_SECRET_KEY
              value: {{ .Values.database.adminPasswordSecret.key | quote }}
            - name: DB_ADMIN_PASSWORD_SECRET_NAMESPACE
              value: {{ .Values.database.adminPasswordSecret.namespace | quote }}
            # Metrics and webhook configuration
            - name: METRICS_PORT
              value: "{{ .Values.metrics.service.port }}"
            - name: WEBHOOK_PORT
              value: "443"
            - name: WEBHOOK_ENABLED
              value: "true"
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "odoo-operator.fullname" . }}-webhook-certs
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
