{{- /* Determine the secret name */ -}}
{{- $secretName := "postgres-clusters" -}}
{{- if and .Values.postgresClustersSecretRef .Values.postgresClustersSecretRef.name -}}
  {{- $secretName = .Values.postgresClustersSecretRef.name -}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-instances
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-migrate-instances
    spec:
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              echo "=== Odoo Operator Instance Migration ==="
              
              # Read the default cluster name from the secret
              echo "Reading default cluster from secret..."
              SECRET_DATA=$(kubectl get secret {{ $secretName }} -n {{ .Release.Namespace }} -o jsonpath='{.data.clusters\.yaml}' | base64 -d)
              DEFAULT_CLUSTER=$(echo "$SECRET_DATA" | grep -B1 "default: true" | head -1 | tr -d ' :')
              
              if [ -z "$DEFAULT_CLUSTER" ]; then
                echo "ERROR: No default cluster found in secret"
                exit 1
              fi
              echo "Default cluster: $DEFAULT_CLUSTER"
              
              # Migrate instances without database.cluster to use default cluster
              echo "Checking for OdooInstances without database.cluster..."
              
              # Get all instances and check each one
              INSTANCES=$(kubectl get odooinstances.bemade.org --all-namespaces -o json 2>/dev/null | \
                jq -r '.items[] | select(.spec.database == null or .spec.database.cluster == null) | "\(.metadata.namespace) \(.metadata.name)"' || echo "")
              
              if [ -z "$INSTANCES" ]; then
                echo "No instances need migration."
              else
                echo "$INSTANCES" | while read namespace name; do
                  if [ -n "$namespace" ] && [ -n "$name" ]; then
                    echo "Patching $namespace/$name to set database.cluster=$DEFAULT_CLUSTER"
                    kubectl patch odooinstance.bemade.org "$name" -n "$namespace" \
                      --type=merge \
                      -p "{\"spec\":{\"database\":{\"cluster\":\"$DEFAULT_CLUSTER\"}}}"
                  fi
                done
              fi
              
              echo "=== Migration complete ==="
