{{- if .Values.openclaw.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "openclaw.fullname" . }}-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.openclaw.hostname }}`)
      priority: 10
      services:
        - kind: Service
          name: {{ include "openclaw.fullname" . }}
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: {{ .Values.openclaw.port }}
          scheme: http
      middlewares:
        - name: {{ include "openclaw.fullname" . }}-headers
          namespace: {{ .Release.Namespace }}
        {{- if .Values.openclaw.ingress.hsts.enabled }}
        - name: {{ include "openclaw.fullname" . }}-hsts
          namespace: {{ .Release.Namespace }}
        {{- end }}
  tls:
    secretName: {{ include "openclaw.fullname" . }}-cert
{{- end }}
