{{- if .Values.openclaw.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openclaw-headers
  namespace: {{ .Release.Namespace }}
  labels:
    app: openclaw
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end }}
