{{- if .Values.openclaw.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.openclaw.persistence.storageClass }}
  storageClassName: {{ .Values.openclaw.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.openclaw.persistence.size }}
{{- end }}
