apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-operator
  namespace: {{ .Release.Namespace }}
rules:
  # Permissions for managing Odoo custom resources
  - apiGroups: ["odoo.bemade.org"]
    resources: ["odooinstances"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Permissions for managing status subresources
  - apiGroups: ["odoo.bemade.org"]
    resources: ["odooinstances/status"]
    verbs: ["get", "update", "patch"]
  
  # Permissions for managing core Kubernetes resources
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Permissions for managing apps resources
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Permissions for managing batch resources
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Permissions for managing networking resources
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Permissions for managing namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  # Permissions for customresourcedefinitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # Permissions for certificates
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]