apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak - Identity and Access Management
type: application
version: 0.1.0
appVersion: "26.0"
home: https://git.bemade.org/bemade/helm-charts
sources:
  - https://git.bemade.org/bemade/helm-charts
  - https://www.keycloak.org/
maintainers:
  - name: Bemade Inc.
    url: https://git.bemade.org
    email: it@bemade.org
