apiVersion: v2
name: odoo-instance
version: 0.3.0
description: A Helm chart for creating Odoo instances with the Odoo Operator
type: application
home: https://github.com/bemadecode/odoo-operator
sources:
  - https://github.com/bemadecode/odoo-operator
maintainers:
  - name: Bemade Inc.
    url: https://bemade.org
    email: it@bemade.org
