apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-pgloader
  namespace: {{ .Release.Namespace }}
data:
  pgloader.load: |
    LOAD DATABASE
        FROM mssql://{{MSSQL_USER}}sa:{{MSSQL_PASS}}@{{MSSQL_HOST}}:1433/{{MSSQL_DB}}
        INTO postgresql://{{PG_USER}}:{{PG_PASSWORD}}@{{PG_HOST}}:5432/{{PG_DB}}

     WITH include drop, create tables, create indexes, reset sequences,
          workers = 2, concurrency = 1, batch rows = 5000, batch size = 10MB,
          prefetch rows = 1000

     SET maintenance_work_mem to '128MB', work_mem to '12MB', search_path to 'public'

     CAST type datetime to timestamptz
          drop default drop not null using zero-dates-to-null,
          type date drop not null drop default using zero-dates-to-null

     BEFORE LOAD DO
     $$ create schema if not exists public; $$;
