apiVersion: batch/v1
kind: Job
metadata:
  name: pgloader
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      initContainers:
      - name: wait-for-postgres
        image: postgres:{{ .Values.postgresql.version | default "latest" }}
        command: ['sh', '-c', 'until pg_isready -h postgres -U postgres; do echo waiting for postgres; sleep 2; done;']
        env:
          - name: PGPASSWORD
            value: "pgpassword"
      - name: wait-for-mssql
        image: busybox
        command: ['sh', '-c', 'until nc -z mssql-server 1433; do echo waiting for mssql; sleep 2; done;']
      - name: mssql-restore-db
        image: docker.bemade.org/bemade/docker-mssql-tools:0.0.1-amd64
        env:
        - name: SA_PASSWORD
          value: "mssqlP4ss"
        - name: ACCEPT_EULA
          value: "Y"
        - name: DB_NAME
          value: {{ .Values.mssql.dbName | quote }}
        - name: BAKFILE
          value: "backup.bak"
        command: ["/bin/bash", "-c", "--"]
        args:
        - |
          set +e
          until /opt/mssql-tools18/bin/sqlcmd -C -S mssql-server -U SA -P "$SA_PASSWORD" -Q "SELECT 1" &> /dev/null;
          do
            echo "Waiting for MSSQL Server to be available...";
            sleep 3;
          done;
          echo "MSSQL Server is now available.";
          echo "Restoring the database...";
          DB_LOG_NAME="$DB_NAME""_log"
          # Drop and restore the database
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "
          IF DB_ID('$DBNAME') IS NOT NULL
          BEGIN
              ALTER DATABASE Pneuprod SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
              DROP DATABASE Pneuprod;
          END
          GO

          RESTORE FILELISTONLY
          FROM DISK = '/backup/backup.bak'
          GO

          RESTORE DATABASE Pneuprod
          FROM DISK = '/backup/backup.bak'
          WITH MOVE '$DB_NAME' TO '/var/opt/mssql/data/Pneuprod.mdf',
               MOVE '$DB_LOG_NAME' TO '/var/opt/mssql/data/Pneuprod_log.ldf',
               REPLACE, RECOVERY;
          GO
          "
      containers:
      - name: pgloader
        image: dimitri/pgloader
        volumeMounts:
        - name: pgloader-script
          mountPath: /pgloader.load
          subPath: pgloader.load
        command: ["pgloader", "--verbose", "--debug", "/pgloader.load"]
        env:
          - name: "MSSQL_HOST"
            value: "mssql-server"
          - name: "MSSQL_USER"
            value: "SA"
          - name: "MSSQL_PASS"
            value: "mssqlP4ss"
          - name: "MSSQL_DB"
            value: {{ .Values.mssql.dbName }}
          - name: "PG_HOST"
            value: "postgres"
          - name: "PG_USER"
            value: "postgres"
          - name: "PG_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: pgpassword
          - name: "PG_DB"
            value: {{ .Values.postgresql.dbName }}
      restartPolicy: OnFailure
      volumes:
      - name: pgloader-script
        configMap:
          name: cm-pgloader
