apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.size | default "20Gi" }}
  storageClassName: {{ .Values.mssql.storageClassName | default "non-replicated-storage" | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.bakVolumeSize | default "20Gi" }}
  storageClassName: {{ .Values.mssql.storageClassName | default "non-replicated-storage" | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.size | default "20Gi" }}
  storageClassName: {{ .Values.postgresql.storageClassName | default "non-replicated-storage" | quote }}
