apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  s3AccessKeyId: {{ .Values.mssql.s3AccessKeyId }}
  s3SecretAccessKey: {{ .Values.mssql.s3SecretAccessKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
stringData:
  sa-password: m55qLp455

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  pgpassword: p05stgr3sqLp455
