apiVersion: bemade.org/v1
kind: OdooInstance
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image | required "Field image is required." }}
  imagePullSecret: {{ .Values.imagePullSecret }}
  adminPassword: {{ .Values.adminPassword | required "Field adminPassword is required." }}
  replicas: {{ .Values.replicas | default 1}}
  resources:
    requests:
      cpu: {{ .Values.resources.requests.cpu | default "200m" }}
      memory: {{ .Values.resources.requests.memory | default "250Mi" }}
    limits:
      cpu: {{ .Values.resources.limits.cpu | default "2000m" }}
      memory: {{ .Values.resources.limits.memory | default "2Gi" }}
  filestore:
    storageSize: {{ .Values.filestore.storageSize | default "2Gi" }}
    storageClass: {{ .Values.filestore.storageClass | default "standard" }}
  ingress:
    host: {{ .Values.ingress.host | required "Field ingress.host is required. This is the FQDN for the Odoo instance." }}
    issuer: {{ .Values.ingress.issuer | required "Field ingress.issuer is required. This is generally a ClusterIssuer name." }}
  configOptions:
    {{- toYaml .Values.configOptions | nindent 4 }}