apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-db-user-{{ .Release.Name }}-{{ .Values.odoo.production.hostname }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.odoo.database.adminSecretNamespace }}
      serviceAccountName: {{ .Release.Name }}-db-jobs
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: cleanup-db-user
          image: postgres:16.1
          command: ["/bin/bash", "/scripts/cleanup-db-user.sh"]
          env:
            - name: HOST
              value: {{ .Values.odoo.database.host | quote }}
            - name: PORT
              value: {{ .Values.odoo.database.port | quote }}
            - name: ADMIN_USER
              value: {{ .Values.odoo.database.adminUser | quote }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.odoo.database.adminSecretNamespace }}
                  name: {{ .Release.Name }}-postgres-secret
                  {{- else }}
                  name: {{ .Values.odoo.database.adminSecretName }}
                  {{- end }}
                  key: {{ .Values.odoo.database.adminPasswordKey }}
            - name: USER_TO_DROP
              value: {{ printf "%s-%s-%s" .Release.Namespace .Release.Name .Values.odoo.production.hostname | lower | replace "_" "-" | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.odoo.database.adminSecretNamespace }}
                  name: {{ .Release.Name }}-postgres-secret
                  {{- else }}
                  name: {{ .Values.odoo.database.adminSecretName }}
                  {{- end }}
                  key: {{ .Values.odoo.database.adminPasswordKey }}
          volumeMounts:
            - name: cleanup-db-script
              mountPath: /scripts
      volumes:
        - name: cleanup-db-script
          configMap:
            name: cleanup-db-script
