apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-removed-users-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.odoo.database.adminSecretNamespace }}
      serviceAccountName: {{ .Release.Name }}-db-jobs
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: cleanup-removed-users
          image: postgres:16.1
          command: ["/bin/bash", "/scripts/cleanup-removed-users.sh"]
          env:
            - name: HOST
              value: {{ .Values.odoo.database.host | quote }}
            - name: PORT
              value: {{ .Values.odoo.database.port | quote }}
            - name: ADMIN_USER
              value: {{ .Values.odoo.database.adminUser | quote }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.odoo.database.adminSecretNamespace }}
                  name: {{ .Release.Name }}-postgres-secret
                  {{- else }}
                  name: {{ .Values.odoo.database.adminSecretName }}
                  {{- end }}
                  key: {{ .Values.odoo.database.adminPasswordKey }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: RELEASE_NAME
              value: {{ .Release.Name | quote }}
            - name: CURRENT_USERS
              value: {{ (printf "%s-%s-%s" .Release.Namespace .Release.Name .Values.odoo.production.hostname | lower | replace "_" "-") }}{{- range .Values.odoo.staging }},{{ printf "%s-%s-%s" $.Release.Namespace $.Release.Name .hostname | lower | replace "_" "-" }}{{- end }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.odoo.database.adminSecretNamespace }}
                  name: {{ .Release.Name }}-postgres-secret
                  {{- else }}
                  name: {{ .Values.odoo.database.adminSecretName }}
                  {{- end }}
                  key: {{ .Values.odoo.database.adminPasswordKey }}
          volumeMounts:
            - name: cleanup-removed-users-script
              mountPath: /scripts
      volumes:
        - name: cleanup-removed-users-script
          configMap:
            name: cleanup-removed-users-script
