{{- if .Values.odoo.database.adminSecretNamespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-postgres-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.odoo.database.adminSecretNamespace }}
      serviceAccountName: {{ .Release.Name }}-db-jobs
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: copy-postgres-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              
              # Get the secret from the source namespace
              echo "Getting secret from {{ .Values.odoo.database.adminSecretNamespace }} namespace"
              SECRET_DATA=$(kubectl get secret -n {{ .Values.odoo.database.adminSecretNamespace }} {{ .Values.odoo.database.adminSecretName }} -o jsonpath="{.data.{{ .Values.odoo.database.adminPasswordKey }}}")
              
              if [ -z "$SECRET_DATA" ]; then
                echo "Error: Could not find {{ .Values.odoo.database.adminPasswordKey }} in secret {{ .Values.odoo.database.adminSecretName }} in namespace {{ .Values.odoo.database.adminSecretNamespace }}"
                exit 1
              fi
              
              # Check if the secret exists in the target namespace
              if kubectl get secret {{ .Release.Name }}-postgres-secret -n {{ .Release.Namespace }} &> /dev/null; then
                echo "Updating existing secret in {{ .Release.Namespace }} namespace"
                # Update the existing secret
                kubectl patch secret {{ .Release.Name }}-postgres-secret -n {{ .Release.Namespace }} --type=merge -p "{\"data\":{\"{{ .Values.odoo.database.adminPasswordKey }}\": \"$SECRET_DATA\"}}"
              else
                echo "Creating new secret in {{ .Release.Namespace }} namespace"
                # Create a new secret
                PASSWORD=$(echo $SECRET_DATA | base64 --decode)
                kubectl create secret generic {{ .Release.Name }}-postgres-secret -n {{ .Release.Namespace }} --from-literal={{ .Values.odoo.database.adminPasswordKey }}="$PASSWORD"
              fi
              
              echo "Secret successfully copied to {{ .Release.Namespace }} namespace"
{{- end }}
