{{- if .Values.odoo.database.pgpool.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-pgpool-user-{{ .Release.Name }}-{{ .Values.odoo.production.hostname }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"  # Run after the init-db-user job (weight 0)
spec:
  template:
    spec:
      {{- if .Values.odoo.database.adminSecretNamespace }}
      serviceAccountName: {{ .Release.Name }}-db-jobs
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: init-pgpool-user
          image: bitnami/kubectl:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Use the database host directly from values
              PGPOOL_HOST={{ .Values.odoo.database.host | quote }}
              
              echo "Using pgpool host: $PGPOOL_HOST"
              
              # Find a pgpool pod to execute commands on
              PGPOOL_POD=$(kubectl get pods -l app.kubernetes.io/name=postgresql-ha,app.kubernetes.io/component=pgpool -o jsonpath='{.items[0].metadata.name}' -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }})
              
              if [ -z "$PGPOOL_POD" ]; then
                echo "Error: No pgpool pods found"
                exit 1
              fi
              
              echo "Found pgpool pod: $PGPOOL_POD"
              
              # Create a temporary file with a random name for security
              TEMP_FILE=$(mktemp)
              
              # Create the user entry in plain text format
              echo "{{ .NEW_USER }}:$NEW_PASSWORD" > $TEMP_FILE
              
              # Create a temporary file on the pgpool pod
              POD_TEMP_FILE=$(kubectl exec $PGPOOL_POD -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }} -- mktemp)
              if [ $? -ne 0 ]; then
                echo "Error: Failed to create temporary file on pgpool pod"
                rm $TEMP_FILE
                exit 1
              fi
              
              # Copy the file to the pgpool pod
              kubectl cp $TEMP_FILE $PGPOOL_POD:$POD_TEMP_FILE -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }}
              if [ $? -ne 0 ]; then
                echo "Error: Failed to copy file to pgpool pod"
                rm $TEMP_FILE
                exit 1
              fi
              
              # Add the user to pool_passwd using cat
              echo "Adding user {{ .NEW_USER }} to pool_passwd"
              kubectl exec $PGPOOL_POD -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }} -- bash -c "cat $POD_TEMP_FILE >> /opt/bitnami/pgpool/etc/pool_passwd"
              if [ $? -ne 0 ]; then
                echo "Error: Failed to update pool_passwd file"
                rm $TEMP_FILE
                kubectl exec $PGPOOL_POD -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }} -- rm $POD_TEMP_FILE
                exit 1
              fi
              
              # Remove the temporary files
              kubectl exec $PGPOOL_POD -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }} -- rm $POD_TEMP_FILE
              rm $TEMP_FILE
              
              # Reload pgpool configuration
              echo "Reloading pgpool configuration"
              kubectl exec $PGPOOL_POD -n {{ .Values.odoo.database.adminSecretNamespace | default .Release.Namespace }} -- pgpool -f /opt/bitnami/pgpool/conf/pgpool.conf reload
              
              echo "Pgpool user setup completed successfully"
          env:
            - name: NEW_USER
              value: {{ printf "%s-%s-%s" .Release.Namespace .Release.Name .Values.odoo.production.hostname | lower | replace "_" "-" | quote }}
            - name: NEW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          # No volume mounts needed - using service account for authentication
  backoffLimit: 4
{{- end }}
