{{- /* Determine which config method is being used */ -}}
{{- $hasInlineClusters := and .Values.postgresClusters (gt (len .Values.postgresClusters) 0) -}}
{{- $hasSecretRef := and .Values.postgresClustersSecretRef .Values.postgresClustersSecretRef.name -}}

{{- /* Validate exactly one method is configured */ -}}
{{- if and $hasInlineClusters $hasSecretRef -}}
  {{- fail "Cannot specify both postgresClusters and postgresClustersSecretRef - choose one" -}}
{{- end -}}
{{- if and (not $hasInlineClusters) (not $hasSecretRef) -}}
  {{- fail "Either postgresClusters or postgresClustersSecretRef.name must be configured" -}}
{{- end -}}

{{- /* Only create secret if using inline clusters */ -}}
{{- if $hasInlineClusters -}}
{{- /* Validate exactly one cluster has default: true */ -}}
{{- $defaultCount := 0 -}}
{{- range $name, $config := .Values.postgresClusters -}}
  {{- if $config.default -}}
    {{- $defaultCount = add $defaultCount 1 -}}
  {{- end -}}
{{- end -}}
{{- if ne $defaultCount 1 -}}
  {{- fail (printf "Exactly one PostgreSQL cluster must have 'default: true'. Found %d default clusters." $defaultCount) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-clusters
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  clusters.yaml: |
    {{- range $name, $config := .Values.postgresClusters }}
    {{ $name }}:
      host: {{ $config.host | quote }}
      port: {{ $config.port }}
      adminUser: {{ $config.adminUser | quote }}
      adminPassword: {{ $config.adminPassword | quote }}
      default: {{ $config.default | default false }}
    {{- end }}
{{- end -}}
