apiVersion: v1
kind: Secret
metadata:
  name: postgres-clusters
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  clusters.yaml: |
    {{- toYaml .Values.postgresClusters | nindent 4 }}
