{{ if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    {{ .Values.ingress.hostnames | toYaml}}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certManager.clusterIssuer }}
  secretName: {{ .Release.Name }}-cert
{{ end }}
