apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.odoo.production.hostname }}-repos-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.odoo.filestore.size | default "1Gi" }}
  storageClassName: {{ .storageClassName | default "standard" }}


