apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.odoo.production.hostname }}-repos-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.odoo.repoStorage.size | default "1Gi" }}
  storageClassName: {{ $.Values.odoo.repoStorage.storageClassName | default "longhorn" }}


