apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.odoo.hostname }}-filestore-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.odoo.filestore.storageClassName | default "longhorn" }}
