{{- if .Values.nextcloud.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nextcloud.fullname" . }}-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.nextcloud.hostname }}`)
      kind: Rule
      middlewares:
        - name: {{ include "nextcloud.fullname" . }}-headers
          namespace: {{ .Release.Namespace }}
        - name: {{ include "nextcloud.fullname" . }}-caldav
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ include "nextcloud.fullname" . }}
          port: 80
  tls:
    secretName: {{ include "nextcloud.fullname" . }}-tls
{{- end }}
