{{- if .Values.nextcloud.ingress.enabled }}
# Middleware for CalDAV/CardDAV well-known redirects
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "nextcloud.fullname" . }}-caldav
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://${1}/remote.php/dav"
{{- end }}
