{{- if not .Values.nextcloud.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  nextcloud-username: {{ .Values.nextcloud.admin.username | quote }}
  nextcloud-password: {{ .Values.secrets.adminPassword | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.database.username | quote }}
  db-password: {{ .Values.secrets.databasePassword | quote }}
{{- end }}
---
{{- if and .Values.nextcloud.mail.enabled (not .Values.nextcloud.mail.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-smtp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-username: {{ .Values.nextcloud.mail.smtp.username | default "" | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | quote }}
{{- end }}
---
{{- if and .Values.nextcloud.objectStore.s3.enabled (not .Values.nextcloud.objectStore.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3-access-key: {{ .Values.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | quote }}
{{- end }}
---
{{- if and .Values.redis.enabled (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.secrets.redisPassword | quote }}
{{- end }}
