{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) .Values.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" (dict "component" "oidc" "rootContext" $) | nindent 4 }}
type: Opaque
stringData:
  oidc-secret.config.php: |
    <?php
    $CONFIG = array (
      'oidc_login_client_secret' => '{{ .Values.oidc.clientSecret }}',
    );
{{- end }}
