{{- if and (not .Values.nextcloud.existingSecret.enabled) .Values.nextcloud.password }}
apiVersion: v1
kind: Secret
metadata:
  # Name matches default expected by deployment: {{ include "nextcloud.fullname" . }}
  name: {{ template "nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" (dict "component" "credentials" "rootContext" $) | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.nextcloud.existingSecret.usernameKey | default "nextcloud-username" }}: {{ .Values.nextcloud.username | quote }}
  {{ .Values.nextcloud.existingSecret.passwordKey | default "nextcloud-password" }}: {{ .Values.nextcloud.password | quote }}
  {{- if .Values.nextcloud.existingSecret.tokenKey }}
  {{ .Values.nextcloud.existingSecret.tokenKey }}: {{ .Values.nextcloud.token | default "" | quote }}
  {{- end }}
  {{- if .Values.nextcloud.mail.enabled }}
  {{ .Values.nextcloud.existingSecret.smtpUsernameKey | default "smtp-username" }}: {{ .Values.nextcloud.mail.smtp.username | default "" | quote }}
  {{ .Values.nextcloud.existingSecret.smtpPasswordKey | default "smtp-password" }}: {{ .Values.nextcloud.mail.smtp.password | default "" | quote }}
  {{ .Values.nextcloud.existingSecret.smtpHostKey | default "smtp-host" }}: {{ .Values.nextcloud.mail.smtp.host | default "" | quote }}
  {{- end }}
{{- end }}
