{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" (dict "component" "redis" "rootContext" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.port | default 6379 }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "nextcloud.selectorLabels" (dict "component" "redis" "rootContext" $) | nindent 4 }}
{{- end }}
