apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ca.name }}
  namespace: {{ .Values.ca.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  isCA: true
  commonName: {{ .Values.ca.commonName }}
  duration: {{ .Values.ca.duration }}
  secretName: {{ .Values.ca.name }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.ca.name }}-issuer
    kind: {{ ternary "ClusterIssuer" "Issuer" .Values.ca.clusterWide }}
    group: cert-manager.io
