apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  masterPassword: {{ .Values.odoo.masterPassword | b64enc }}
  {{- $secretObj := lookup "v1" "Secret" .Release.Namespace "credentials" -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  superUserPassword: {{- if hasKey $secretData "superUserPassword" }}{{ $secretData.superUserPassword }}{{- else }}{{ randAlphaNum 32 | b64enc }}{{- end }}
  password: {{- if hasKey $secretData "password" }}{{ $secretData.password }}{{- else }}{{ randAlphaNum 32 | b64enc }}{{- end }}
