apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  superUserPassword: {{ randAlphaNum 32 | quote }}
  password: {{ randAlphaNum 32 | quote }}
  masterPassword: {{ .Values.odoo.masterPassword }}
