apiVersion: v1
kind: ConfigMap
metadata:
  name: pull-production-db
  namespace: {{ .Release.Namespace }}
data:
  pull-production-db.sh: |
    #!/bin/bash

    BACKUP_FILE="/mnt/prod-backup/backup.zip"


    if [ -f "$BACKUP_FILE" ]; then
      rm "$BACKUP_FILE"
    fi
    curl -o "$BACKUP_FILE" -X POST \
      -F "master_pwd=$MASTER_PW" \
      -F"name=$PROD_DB" \
      -F "backup_format=zip" \
      "http://$PROD_HOST/web/database/backup"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-db
  namespace: {{ .Release.Namespace }}
data:
  restore-db.sh: |
    #!/bin/bash

    BACKUP_FILE="/mnt/prod-backup/backup.zip"
    EXTRACT_DIR="/tmp/odoo_backup"

    # Function to restore the database
    restore_database() {
      echo "Restoring database $DB_NAME..."
      createdb -U "$PG_USER" -h "$PG_HOST" "$DB_NAME"
      pg_restore -U "$PG_USER" -h "$PG_HOST" -d "$DB_NAME" "$EXTRACT_DIR/db.dump"
    }

    # Function to copy the filestore
    copy_filestore() {
      echo "Copying filestore to $FILESTORE_DEST_DIR/$DB_NAME..."
      chown -R odoo:odoo /var/lib/odoo
      cp -r "$EXTRACT_DIR/filestore" "$FILESTORE_DEST_DIR/$DB_NAME"
    }

    # Check if the database already exists
    if psql -U "$PG_USER" -h "$PG_HOST" -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
      echo "Database $DB_NAME already exists. Dropping database."
      dropdb -U "$PG_USER" -h "$PG_HOST" "$DB_NAME"
    fi
    unzip "$BACKUP_FILE" -d "$EXTRACT_DIR"
    restore_database

    # Check if the filestore for the database already exists
    if [ -d "$FILESTORE_DEST_DIR/$DB_NAME" ]; then
      echo "Filestore for $DB_NAME already exists. Deleting."
      rm -rf "$FILESTORE_DEST_DIR/$DB_NAME"
    fi
    echo "Copying filestore..."
    copy_filestore

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: copy-production-db
  namespace: {{ .Release.Namespace }}
data:
  copy-production-db.sh: |
    #!/bin/bash

    # Check if the database already exists
    DB_EXISTS=$(psql -U "$POSTGRES_USER" -h localhost -lqt | cut -d \| -f 1 | grep -w "$POSTGRES_DB" | wc -l)

    if [ "$DB_EXISTS" -eq 1 ]; then
        echo "Database $POSTGRES_DB already exists in staging. No action needed."
    else
        echo "Database $POSTGRES_DB not found in staging. Copying from production database..."
        pg_dump -h $PROD_HOST -U $POSTGRES_USER -d $POSTGRES_DB | psql -U $POSTGRES_USER -h localhost -d $POSTGRES_DB
        echo "Database copied successfully."
    fi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: {{ .Release.Namespace }}
data:
  init-db-user.sh: |
    #!/bin/bash
    set -e

    # Environment variables passed to the container
    HOST=${HOST}
    USER=${USER}
    PASSWORD=${PASSWORD}

    psql -v ON_ERROR_STOP=1 --host="$HOST" --username="postgres" --dbname="postgres" <<-EOSQL
    DO \$\$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '$USER') THEN
        CREATE USER $USER WITH PASSWORD '$PASSWORD' CREATEDB;
      END IF;
    END
    \$\$;
    EOSQL
