apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: {{ .Release.Namespace }}
data:
  primary_init_script.sh: |
    #!/bin/bash
    set -e

    dt=$(date '+%d/%m/%Y %H:%M:%S');
    echo "$dt - Running init script the 1st time Primary PostgreSql container is created...";

    customUserName="$ODOO_USER"

    echo "$dt - Running: psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname postgres ...";

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    CREATE USER $customUserName WITH PASSWORD '$ODOO_USER_PASSWORD';
    \connect postgres;
    ALTER USER $ODOO_USER WITH CREATEDB
    EOSQL

    echo "$dt - Init script is completed";
