apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.odoo.filestore.size | default "10Gi" }}
  {{- if .Values.odoo.filestore.storageClassName }}
  storageClassName: {{ .Values.odoo.filestore.storageClassName }}
  {{- end }}
