apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  superuserName: {{ .Values.odoo.db.superuser }}
  superuserPassword: {{ .Values.odoo.db.superuserPassword }}
