apiVersion: odoo.bemade.org/v1
kind: OdooInstance
metadata:
  name: custom
  namespace: default
spec:
  version: "17.0"
  replicas: 2
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  database:
    storageSize: "10Gi"
    storageClass: "standard"
  filestore:
    storageSize: "20Gi"
    storageClass: "standard"
  addons:
    - repo: "https://github.com/OCA/web"
      branch: "17.0"
    - repo: "https://github.com/OCA/server-tools"
      branch: "17.0"
    - repo: "https://github.com/bemade/custom-addons"
      branch: "main"
  ingress:
    enabled: true
    hostname: "custom.odoo.example.com"
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  env:
    - name: ODOO_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: odoo-admin-secret
          key: password
    - name: TZ
      value: "America/New_York"
    - name: ODOO_DB_HOST
      value: "postgres"
    - name: ODOO_DB_PORT
      value: "5432"
    - name: ODOO_DB_USER
      valueFrom:
        secretKeyRef:
          name: odoo-db-secret
          key: username
    - name: ODOO_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: odoo-db-secret
          key: password
