apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitsyncs.bemade.org
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: bemade.org
  names:
    kind: GitSync
    listKind: GitSyncList
    plural: gitsyncs
    singular: gitsync
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - repository
              properties:
                repository:
                  type: string
                  description: "Git repository URL to clone"
                branch:
                  type: string
                  default: "main"
                  description: "Branch to checkout"
                sshSecret:
                  type: string
                  description: "Name of the secret containing SSH key (optional)"
                odooInstance:
                  type: string
                  description: "Name of the OdooInstance to trigger updates for (optional)"
