apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: odooinstances.bemade.org
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: bemade.org
  names:
    kind: OdooInstance
    listKind: OdooInstanceList
    plural: odooinstances
    singular: odooinstance
    shortNames:
      - odoo
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
                - ingress
                - replicas
                - adminPassword
              properties:
                image:
                  type: string
                  description: "Odoo Docker image to use."
                  default: "odoo:18.0"
                imagePullSecret:
                  type: string
                  description: "Image pull secret to use."
                adminPassword:
                  type: string
                  description: "Odoo database administrator password to use."
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                  description: "Number of Odoo replicas"
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: 200m
                        memory:
                          type: string
                          default: 250Mi
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: 2000m
                        memory:
                          type: string
                          default: 2Gi
                filestore:
                  type: object
                  properties:
                    storageSize:
                      type: string
                      default: "2Gi"
                    storageClass:
                      type: string
                      default: standard
                ingress:
                  type: object
                  required:
                    - hosts
                    - issuer
                  properties:
                    hosts:
                      type: array
                      items:
                        type: string
                      description: "The fully qualified domain names (FQDN) for this host."
                    issuer:
                      type: string
                      description: "The name of the ClusterIssuer to user to issue the TLS certificate."
                configOptions:
                  type: object
                  description: "Options for the odoo.conf file"
                  additionalProperties:
                    type: string
                  example:
                    workers: "2"
                    limit_time_real: "0"
                    limit_time_cpu: "0"
                initialization:
                  type: object
                  description: "Database initialization configuration. Only processed on first creation."
                  properties:
                    mode:
                      type: string
                      enum: ["fresh", "restore"]
                      default: "fresh"
                      description: "Initialization mode: 'fresh' for empty database, 'restore' to copy from another Odoo instance"
                    restore:
                      type: object
                      description: "Restore configuration when mode is 'restore'"
                      properties:
                        url:
                          type: string
                          description: "URL of the source Odoo instance (e.g., https://production.odoo.com)"
                        sourceDatabase:
                          type: string
                          description: "Name of the database to restore from the source instance"
                        masterPassword:
                          type: string
                          description: "Master password of the source Odoo instance"
                        withFilestore:
                          type: boolean
                          default: true
                          description: "Whether to include filestore in the restore"
                        neutralize:
                          type: boolean
                          default: true
                          description: "Whether to neutralize the database (reset UUIDs, secrets, etc.)"
                upgrade:
                  type: object
                  required:
                    - modules
                  properties:
                    database:
                      type: string
                      description: "DEPRECATED: Database name is now auto-generated from instance UID. This field is ignored."
                    modules:
                      type: array
                      items:
                        type: string
                    time:
                      type: string
                      description: "The date and time the upgrade should be performed. This must be in the format YYYY-MM-DDTHH:MM:SSZ."
                      format: date-time
                sync:
                  type: object
                  description: "Configuration for Git repository synchronization (uses gitProject for repository details)"
                  properties:
                    enabled:
                      type: boolean
                      description: "When set to true, triggers a sync operation. Resets to false after sync completes."
                      default: false
                    time:
                      type: string
                      description: "The scheduled time for sync. Format: YYYY-MM-DDTHH:MM:SSZ."
                      format: date-time
                # NOTE: spec.restore has been moved to OdooRestoreJob CRD
                # Use OdooRestoreJob CR to trigger restore operations

            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Running
                    - Upgrading
                    - Restoring
                  default: Running
                message:
                  type: string
                ready:
                  type: boolean
                url:
                  type: string
                lastBackup:
                  type: string
                  format: date-time
                upgradeJob:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: URL
          type: string
          jsonPath: .status.url
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
