apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgpool
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.admin.passwordKey }}: {{ randAlphaNum 16 | b64enc | quote }}
{{- if .Values.admin.generatePasswordHelperFile }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pgpool-password-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgpool
    release: {{ .Release.Name }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
data:
  note.txt: |
    The pgpool admin password was generated automatically.
    To retrieve the password, run:

    kubectl get secret --namespace {{ .Release.Namespace }} {{ .Values.admin.secretName }} -o jsonpath="{.data.{{ .Values.admin.passwordKey }}}" | base64 --decode
{{- end }}
