{{- if .Values.keycloak.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.keycloak.hostname }}`)
      kind: Rule
      middlewares:
        - name: {{ include "keycloak.fullname" . }}-redirect-https
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ include "keycloak.fullname" . }}
          port: {{ .Values.keycloak.httpPort }}
{{- end }}
