{{- if .Values.keycloak.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "keycloak.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
