{{- if not .Values.keycloak.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.database.username | quote }}
  password: {{ .Values.secrets.databasePassword | quote }}
{{- end }}
---
{{- if not .Values.keycloak.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.adminPassword | quote }}
{{- end }}
