apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odoo
  namespace: {{ .Release.Namespace }}
spec:
  secretName: odoo-cert
  dnsNames:
    - {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
  issuerRef:
    name: {{ .Values.odoo.ingress.clusterIssuer }}
    kind: ClusterIssuer
