{{- if .Values.odoo.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Release.Namespace }}

spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
